/**
 * Fullscreen pass — a dual-source kit chunk (Task 112).
 *
 * Answers Task 112's question "why yet another entity?" — NO entity is
 * needed: the fullscreen triangle is GENERATED BY THE SHADER ITSELF from
 * vertex_index (gl_VertexID / @builtin(vertex_index)) — no primitive, no
 * vertex buffer, no attributes. This is an established GPU practice
 * (three vertices computed from the index cover clip space).
 *
 * Dossier §10.3: kit — "a library of dual-source chunks (GLSL/WGSL pairs
 * with identical names) and recipes: fullscreen triangle, blur, …" —
 * this chunk is exactly that "fullscreen triangle".
 *
 * Two names, one semantics:
 *  • GL: drawArrays(TRIANGLES, first=0, count=3) — vertices from gl_VertexID;
 *  • WebGPU: draw(vertexCount=3) — vertices from @builtin(vertex_index).
 *
 * UV: vertex 0 → (0,0), 1 → (2,0), 2 → (0,2) — interpolation yields
 * correct UVs inside the frustum; outside it, the triangle is clipped.
 * Positions: x = 4·(i==1) - 1, y = 4·(i==2) - 1 — the classic
 * oversized triangle (no "seam" on the quad diagonal).
 *
 * Usage: insert the chunk BEFORE your @fragment (WGSL) or concatenate it
 * with your fragment shader (GLSL, ES 3.00). VsOut/vout — a shared struct.
 */

/** GLSL ES 3.00: fullscreen triangle from gl_VertexID. */
export const FULLSCREEN_PASS_GLSL = /* glsl */ `#version 300 es
precision highp float;

out vec2 v_uv;

const vec2 POS[3] = vec2[3](
  vec2(-1.0, -1.0),
  vec2( 3.0, -1.0),
  vec2(-1.0,  3.0)
);

void main() {
  vec2 pos = POS[gl_VertexID];
  v_uv = pos * 0.5 + 0.5;
  gl_Position = vec4(pos, 0.0, 1.0);
}
`

/** WGSL: fullscreen triangle from @builtin(vertex_index). */
export const FULLSCREEN_PASS_WGSL = /* wgsl */ `
struct VsOut {
  @builtin(position) pos: vec4f,
  @location(0) coord: vec2f,
}

@vertex
fn vsMain(@builtin(vertex_index) vi: u32) -> VsOut {
  let POS = array<vec2f, 3>(
    vec2f(-1.0, -1.0),
    vec2f( 3.0, -1.0),
    vec2f(-1.0,  3.0),
  )
  var vout: VsOut
  let p = POS[vi]
  vout.pos = vec4f(p, 0.0, 1.0)
  vout.coord = p * 0.5 + 0.5
  return vout
}
`
