/** scripts/extract-leaf.mjs — the alpha-test demo's asset provenance: the
 *  three.quarks leave.glb (their AlphaTestDemo is a MESH particle — a real
 *  3D leaf, RandomQuat start rotation + Rotation3DOverLife tumble), baked
 *  ONCE into:
 *    demo/quarks/assets/leaves.png        (their embedded PNG, verbatim)
 *    demo/quarks/demos/leaf-geometry.js   (the triangle soup: positions /
 *                                          normals / uvs / vertexCount —
 *                                          the indices resolved)
 *  Run after updating the reference clone:
 *    bun scripts/extract-leaf.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const GLB = '/home/z/my-project/reference/three.quarks/packages/quarks.examples/public/leave.glb'

const buf = readFileSync(GLB)
const dv = new DataView(buf.buffer, buf.byteOffset, buf.byteLength)
let off = 12
const chunks = []
while (off < buf.length) {
  const len = dv.getUint32(off, true)
  chunks.push({ off, len, type: dv.getUint32(off + 4, true) })
  off += 8 + len
}
const json = JSON.parse(buf.subarray(chunks[0].off + 8, chunks[0].off + 8 + chunks[0].len).toString('utf8'))
const binStart = chunks[1].off + 8
const bin = buf.subarray(binStart, binStart + chunks[1].len)

// ── the geometry: POSITION / NORMAL / TEXCOORD_0 + indices → a soup ──────
const view = (i) => {
  const bv = json.bufferViews[i]
  return bin.subarray(bv.byteOffset ?? 0, (bv.byteOffset ?? 0) + bv.byteLength)
}
const prim = json.meshes[0].primitives[0]
const posA = prim.attributes.POSITION
const nrmA = prim.attributes.NORMAL
const uvA = prim.attributes.TEXCOORD_0
const idxA = prim.indices
const imgV = json.images[0].bufferView
const pos = new Float32Array(view(json.accessors[posA].bufferView ?? 0).buffer, view(json.accessors[posA].bufferView ?? 0).byteOffset, json.accessors[posA].count * 3)
const nrm = new Float32Array(view(json.accessors[nrmA].bufferView ?? 0).buffer, view(json.accessors[nrmA].bufferView ?? 0).byteOffset, json.accessors[nrmA].count * 3)
const uv = new Float32Array(view(json.accessors[uvA].bufferView ?? 0).buffer, view(json.accessors[uvA].bufferView ?? 0).byteOffset, json.accessors[uvA].count * 2)
const idx = new Uint16Array(view(json.accessors[idxA].bufferView ?? 0).buffer, view(json.accessors[idxA].bufferView ?? 0).byteOffset, json.accessors[idxA].count)

const triCount = idx.length / 3
const positions = new Float32Array(triCount * 9)
const normals = new Float32Array(triCount * 9)
const uvs = new Float32Array(triCount * 6)
for (let t = 0; t < triCount; t++) {
  for (let k = 0; k < 3; k++) {
    const v = idx[t * 3 + k]
    positions.set(pos.subarray(v * 3, v * 3 + 3), t * 9 + k * 3)
    normals.set(nrm.subarray(v * 3, v * 3 + 3), t * 9 + k * 3)
    uvs.set(uv.subarray(v * 2, v * 2 + 2), t * 6 + k * 2)
  }
}

const fmt = (arr, per) => `[${Array.from(arr, v => (Math.round(v * 1e5) / 1e5).toString()).join(',')}]`
const js = `// leaf-geometry.js — AUTO-GENERATED by scripts/extract-leaf.mjs from the
// three.quarks leave.glb (their AlphaTestDemo's instancingGeometry — a real
// 3D leaf: ${json.accessors[posA].count} verts, ${triCount} tris, alphaMode
// MASK @ cutoff ${json.materials[0].alphaCutoff.toFixed(3)}, doubleSided).
// A plain TRIANGLE SOUP (the glTF indices resolved) — the mesh-particle
// geometry contract of @rune/particles.
export const LEAF = {
  positions: new Float32Array(${fmt(positions, 3)}),
  normals: new Float32Array(${fmt(normals, 3)}),
  uvs: new Float32Array(${fmt(uvs, 2)}),
  vertexCount: ${triCount * 3},
}
`
writeFileSync(join(root, 'demo/quarks/demos/leaf-geometry.js'), js)
writeFileSync(join(root, 'demo/quarks/assets/leaves.png'), view(imgV))
console.log(`leaf: ${triCount} tris (${triCount * 3} soup verts) → demos/leaf-geometry.js; ${view(imgV).length} png bytes → assets/leaves.png`)
